const char* shape_vert_gles2 = "#version 100\n"
    "precision mediump float;\n"
    "precision mediump int;\n"
    "\n"
    "\n"
    "// Uniforms ----------------------\n"
    " uniform mat4 model_view_project;\n"
    " uniform mat4 model_view_project_selected;\n"
    "\n"
    "\n"
    "\n"
    "// Vertex Attributes -------------\n"
    "attribute vec3 vertex;\n"
    "attribute vec2 scale;\n"
    "attribute float rotate;\n"
    "attribute vec3 translate;\n"
    "attribute vec3 color;\n"
    "attribute float state;\n"
    "\n"
    "\n"
    "// Outputs -----------------------\n"
    "varying vec2 out_tex_coord;\n"
    "varying vec4 out_color;\n"
    "\n"
    "\n"
    "// Program -----------------------\n"
    "void main()\n"
    "{\n"
    "    if (bool(state >= 2.0)) {"
    "        out_color = vec4(0.9, 0.9, 0.0, 1.0);"
    "    } else { "
    "        out_color = vec4(color,1.0);\n"
    "    }"
    "    vec3 warped = vertex;\n"
    "    warped.x *= scale.x;\n"
    "    warped.y *= scale.y;\n"
    "    float rx = cos(rotate)*warped.x - sin(rotate)*warped.y;\n"
    "    float ry = sin(rotate)*warped.x + cos(rotate)*warped.y;\n"
    "    warped = vec3(rx, ry, warped.z) + translate;\n"
    "    if (bool(state >= 1.0)) {"
    "        gl_Position = model_view_project_selected*vec4(warped,1.0);\n"
    "    } else {"
    "        gl_Position = model_view_project*vec4(warped,1.0);\n"
    "    }"
    "}\n";

const char * shape_frag_gles2 = "#version 100\n"
    "precision mediump float;\n"
    "precision mediump int;\n"
    "varying vec4 out_color;\n"
    "void main()\n"
    "{\n"
    "    gl_FragColor = out_color;\n"
    "}\n";

